"""Add workspaces and api keys

Revision ID: d935e1518730
Revises: 
Create Date: 2026-07-28 20:32:30.023902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd935e1518730'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_chats_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(), nullable=True))
        batch_op.alter_column('knowledge_base_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_documents_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_documents_knowledge_base_id_knowledge_bases'), 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_documents_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), server_default='user', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_documents_knowledge_base_id_knowledge_bases'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_documents_knowledge_base_id'))
        batch_op.alter_column('knowledge_base_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chats_workspace_id_workspaces'), type_='foreignkey')

    # ### end Alembic commands ###
